"""
AIP444 Lab 4: Structured Outputs & Code Reading
Student Name: Wenjun Wei
Student ID:169010238
Date: 10/09/2026

Description:
This module defines the Pydantic data schemas used to validate and structure 
the flashcards generated by the AI model. It enforces strict typing and field 
descriptions for both individual flashcard objects and the overall response array.
"""

from pydantic import BaseModel, Field

class Flashcard(BaseModel):
    application: str = Field(
        description="A 1-2 sentence real-world scenario where this concept is used or required."
    )
    challenge: str = Field(
        description="A specific, practical problem to solve within the application scenario."
    )
    answer: str = Field(
        description="The correct solution to the challenge with a brief explanation. NOTE: All technical acronyms must be fully expanded."
    )
    evidence: str = Field(
        description="A direct quote from the source notes supporting the correct answer."
    )
    misconception: str = Field(
        description="A typical misconception that a student might make, written as a direct quote of what they might say."
    )
    correction: str = Field(
        description="An explanation of why this misconception is wrong, citing specific facts from the source notes."
    )

class FlashcardResponse(BaseModel):
    flashcards: list[Flashcard] = Field(
        description="An array/list containing the generated Flashcard objects."
    )